### ISSUE TITLE
Atualização de Equipe

### ISSUE THREAD

**Issue by TomazMartins** [SRA-UnBGama/SGD#4]
Caso algum usuário seja cadastrado ou atualizado na aplicação o método initialize_teams(  ) é chamado. Desa forma, as equipes são destruídas e criadas novamente, acabando com todas as configurações já criadas para as equipes antes de sua destruição.

Há a necessidade de prover a esse método a capacidade de efetivamente _atualizar_ as equipes já criadas, ao invés de destruí-las.

**Comment by TomazMartins** [comment]
Testei no programa em execução e não ocorreu o mesmo tipo de erro. Alguém pode tentar reproduzir esse tipo de erro?

**Comment by ricardogtx** [comment]
Sim, ainda está dando o mesmo problema!

**Comment by TomazMartins** [comment]
Você poderia descrever os passos que você utilizou para reproduzir o erro, por favor?

**Comment by ricardogtx** [comment]
Você confirma um usuário, daí depois você cria outro, e quando volta na lista de equipes todos estão desconfirmados.

**Comment by TomazMartins** [comment]
Certo.
Obrigado pela informação.
Arrumarei isso.

**Comment by TomazMartins** [comment]
Foi reaberta, na medida em que o problema não foi resolvido completamente.

**Comment by ricardogtx** [comment]
Qual problema persisti?

**Comment by TomazMartins** [comment]
Aquele em que nós dois estávamos trabalhando. As equipes não estão sendo ordenadas. Ou isso já foi completamente arrumado?

Lembro que a lista capturada estava vindo vazia.

Procede?

**Comment by ricardogtx** [comment]
Bem, parece que aquela função não estávamos usando e no final estava sendo ordenado quando arrumamos os seed, mas não tenho certeza que está 100%, depois verificamos!

**Comment by TomazMartins** [comment]
Sim.
Vamos nos certificar disso antes então.
